apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-mysql-db
  namespace: bookstore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookstore-mysql-db
  template:
    metadata:
      labels:
        app: bookstore-mysql-db
    spec:
      containers:
      - name: mysql
        image: mariadb:10.6
        resources:
          requests:
            memory: "64Mi"
            cpu: "1m"
          limits:
            memory: "128Mi"
            cpu: "5m"
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_DATABASE
          value: "bookstore_db"
        - name: MYSQL_USER
          value: "bookstoreDBA"
        - name: MYSQL_PASSWORD
          value: "PaSSworD"
        - name: MYSQL_ROOT_PASSWORD
          value: "r00tPaSSworD"