apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-order-service
  namespace: bookstore
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  selector:
    matchLabels:
      app: bookstore-order-service
  template:
    metadata:
      labels:
        app: bookstore-order-service
    spec:
      containers:
      - name: order
        image: d1ff1c1le/bookstore-order-service:latest
        resources:
          requests:
            memory: "1Gi"
            cpu: "50m"
          limits:
            memory: "3Gi"
            cpu: "200m"
        ports:
        - containerPort: 7001
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 7001
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 7001
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        env:
        - name: SERVER_PORT
          value: "7001"
        - name: ZIPKIN_HOST
          value: "bookstore-zipkin:9411"
        - name: SPRING_PROFILES_ACTIVE
          value: "docker"
---
apiVersion: v1
kind: Service
metadata:
  name: bookstore-order-service
  namespace: bookstore
spec:
  type: NodePort
  ports:
    - port: 7001
      targetPort: 7001
      nodePort: 30007
  selector:
    app: bookstore-order-service 